site_name: ladis.cloud - mdwiki
docs_dir: docs

site_url: http://127.0.0.1:8088/mdwiki
dev_addr: 127.0.0.1:8088

theme:
  name: mdwiki

plugins:
  - mdwiki:
      log_level: info
      log_format: >-
        %(asctime)s [%(levelname)9s] --- %(name)s: %(message)s

nav:
  - GitHub: https://github.com/ILadis

# for available extensions see:
# https://python-markdown.github.io/extensions/
markdown_extensions:
  - mdwiki
  - smarty
  - footnotes
